Dolibarr\Core\CoreBundle\Entity\LlxAccountingFiscalyear:
    type: entity
    table: llx_accounting_fiscalyear
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        dateStart:
            type: date
            nullable: true
            column: date_start
        dateEnd:
            type: date
            nullable: true
            column: date_end
        statut:
            type: boolean
            nullable: false
            options:
                default: '0'
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        datec:
            type: datetime
            nullable: false
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        fkUserAuthor:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user_author
        fkUserModif:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user_modif
    lifecycleCallbacks: {  }
