Dolibarr\Core\CoreBundle\Entity\LlxBankCateg:
    type: entity
    table: llx_bank_categ
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
    lifecycleCallbacks: {  }
