Dolibarr\Core\CoreBundle\Entity\LlxBoxes:
    type: entity
    table: llx_boxes
    indexes:
        idx_boxes_boxid:
            columns:
                - box_id
        idx_boxes_fk_user:
            columns:
                - fk_user
    uniqueConstraints:
        uk_boxes:
            columns:
                - entity
                - box_id
                - position
                - fk_user
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        position:
            type: smallint
            nullable: false
            options:
                unsigned: false
        boxOrder:
            type: string
            nullable: false
            length: 3
            options:
                fixed: false
            column: box_order
        fkUser:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: fk_user
        maxline:
            type: integer
            nullable: true
            options:
                unsigned: false
        params:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        box:
            targetEntity: LlxBoxesDef
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                box_id:
                    referencedColumnName: rowid
            orphanRemoval: false
    lifecycleCallbacks: {  }
