Dolibarr\Core\CoreBundle\Entity\LlxBoxesDef:
    type: entity
    table: llx_boxes_def
    uniqueConstraints:
        uk_boxes_def:
            columns:
                - file
                - entity
                - note
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        file:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        note:
            type: string
            nullable: true
            length: 130
            options:
                fixed: false
    lifecycleCallbacks: {  }
