Dolibarr\Core\CoreBundle\Entity\LlxCBarcodeType:
    type: entity
    table: llx_c_barcode_type
    uniqueConstraints:
        uk_c_barcode_type:
            columns:
                - code
                - entity
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        libelle:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        coder:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
        example:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
    lifecycleCallbacks: {  }
