Dolibarr\Core\CoreBundle\Entity\LlxCPropalst:
    type: entity
    table: llx_c_propalst
    uniqueConstraints:
        uk_c_propalst:
            columns:
                - code
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 12
            options:
                fixed: false
        label:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
