Dolibarr\Core\CoreBundle\Entity\LlxCTypent:
    type: entity
    table: llx_c_typent
    uniqueConstraints:
        uk_c_typent:
            columns:
                - code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 12
            options:
                fixed: false
        libelle:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
        fkCountry:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_country
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        module:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
        position:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
    lifecycleCallbacks: {  }
