Dolibarr\Core\CoreBundle\Entity\LlxCIncoterms:
    type: entity
    table: llx_c_incoterms
    uniqueConstraints:
        uk_c_incoterms:
            columns:
                - code
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 3
            options:
                fixed: false
        libelle:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
