Dolibarr\Core\CoreBundle\Entity\LlxCEffectif:
    type: entity
    table: llx_c_effectif
    uniqueConstraints:
        uk_c_effectif:
            columns:
                - code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 12
            options:
                fixed: false
        libelle:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        module:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
    lifecycleCallbacks: {  }
