Dolibarr\Core\CoreBundle\Entity\LlxCAccountingCategory:
    type: entity
    table: llx_c_accounting_category
    uniqueConstraints:
        uk_c_accounting_category:
            columns:
                - code
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
        label:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        rangeAccount:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: range_account
        sens:
            type: boolean
            nullable: false
            options:
                default: '0'
        categoryType:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: category_type
        formula:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        position:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        fkCountry:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_country
        active:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '1'
    lifecycleCallbacks: {  }
