Dolibarr\Core\CoreBundle\Entity\LlxCPaiement:
    type: entity
    table: llx_c_paiement
    uniqueConstraints:
        uk_c_paiement_code:
            columns:
                - entity
                - code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        code:
            type: string
            nullable: false
            length: 6
            options:
                fixed: false
        libelle:
            type: string
            nullable: true
            length: 62
            options:
                fixed: false
        type:
            type: smallint
            nullable: true
            options:
                unsigned: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        accountancyCode:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: accountancy_code
        module:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
        position:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
    lifecycleCallbacks: {  }
