Dolibarr\Core\CoreBundle\Entity\LlxCExpTaxCat:
    type: entity
    table: llx_c_exp_tax_cat
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            nullable: false
            length: 48
            options:
                fixed: false
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        active:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
    lifecycleCallbacks: {  }
