Dolibarr\Core\CoreBundle\Entity\LlxCShipmentMode:
    type: entity
    table: llx_c_shipment_mode
    uniqueConstraints:
        uk_c_shipment_mode:
            columns:
                - code
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        code:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        libelle:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        tracking:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        active:
            type: boolean
            nullable: true
            options:
                default: '0'
        module:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
    lifecycleCallbacks: {  }
