Dolibarr\Core\CoreBundle\Entity\LlxCAvailability:
    type: entity
    table: llx_c_availability
    uniqueConstraints:
        uk_c_availability:
            columns:
                - code
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        label:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
