Dolibarr\Core\CoreBundle\Entity\LlxEvents:
    type: entity
    table: llx_events
    indexes:
        idx_events_dateevent:
            columns:
                - dateevent
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        type:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        dateevent:
            type: datetime
            nullable: true
        fkUser:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user
        description:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        ip:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        userAgent:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: user_agent
        fkObject:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_object
    lifecycleCallbacks: {  }
