Dolibarr\Core\CoreBundle\Entity\LlxFactureFournDet:
    type: entity
    table: llx_facture_fourn_det
    indexes:
        idx_facture_fourn_det_fk_facture:
            columns:
                - fk_facture_fourn
        idx_facture_fourn_det_fk_product:
            columns:
                - fk_product
        idx_facture_fourn_det_fk_code_ventilation:
            columns:
                - fk_code_ventilation
        fk_facture_fourn_det_fk_unit:
            columns:
                - fk_unit
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fkParentLine:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_parent_line
        fkProduct:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_product
        ref:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        label:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        puHt:
            type: float
            nullable: true
            precision: 24
            scale: 8
            column: pu_ht
        puTtc:
            type: float
            nullable: true
            precision: 24
            scale: 8
            column: pu_ttc
        qty:
            type: float
            nullable: true
            precision: 10
            scale: 0
        remisePercent:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: remise_percent
        vatSrcCode:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
                default: ''
            column: vat_src_code
        tvaTx:
            type: float
            nullable: true
            precision: 6
            scale: 3
            column: tva_tx
        localtax1Tx:
            type: float
            nullable: true
            precision: 6
            scale: 3
            options:
                default: '0.000'
            column: localtax1_tx
        localtax1Type:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: localtax1_type
        localtax2Tx:
            type: float
            nullable: true
            precision: 6
            scale: 3
            options:
                default: '0.000'
            column: localtax2_tx
        localtax2Type:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: localtax2_type
        totalHt:
            type: float
            nullable: true
            precision: 24
            scale: 8
            column: total_ht
        tva:
            type: float
            nullable: true
            precision: 24
            scale: 8
        totalLocaltax1:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
            column: total_localtax1
        totalLocaltax2:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
            column: total_localtax2
        totalTtc:
            type: float
            nullable: true
            precision: 24
            scale: 8
            column: total_ttc
        productType:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: product_type
        dateStart:
            type: datetime
            nullable: true
            column: date_start
        dateEnd:
            type: datetime
            nullable: true
            column: date_end
        infoBits:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: info_bits
        fkCodeVentilation:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: fk_code_ventilation
        specialCode:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: special_code
        rang:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        importKey:
            type: string
            nullable: true
            length: 14
            options:
                fixed: false
            column: import_key
        fkMulticurrency:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_multicurrency
        multicurrencyCode:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: multicurrency_code
        multicurrencySubprice:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
            column: multicurrency_subprice
        multicurrencyTotalHt:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
            column: multicurrency_total_ht
        multicurrencyTotalTva:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
            column: multicurrency_total_tva
        multicurrencyTotalTtc:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
            column: multicurrency_total_ttc
    manyToOne:
        fkFactureFourn:
            targetEntity: LlxFactureFourn
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_facture_fourn:
                    referencedColumnName: rowid
            orphanRemoval: false
        fkUnit:
            targetEntity: LlxCUnits
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_unit:
                    referencedColumnName: rowid
            orphanRemoval: false
    lifecycleCallbacks: {  }
