Dolibarr\Core\CoreBundle\Entity\LlxLoan:
    type: entity
    table: llx_loan
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        datec:
            type: datetime
            nullable: true
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        label:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
        fkBank:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_bank
        capital:
            type: float
            nullable: false
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
        datestart:
            type: date
            nullable: true
        dateend:
            type: date
            nullable: true
        nbterm:
            type: float
            nullable: true
            precision: 10
            scale: 0
        rate:
            type: float
            nullable: false
            precision: 10
            scale: 0
        notePrivate:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: note_private
        notePublic:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: note_public
        capitalPosition:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
            column: capital_position
        datePosition:
            type: date
            nullable: true
            column: date_position
        paid:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '0'
        accountancyAccountCapital:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: accountancy_account_capital
        accountancyAccountInsurance:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: accountancy_account_insurance
        accountancyAccountInterest:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: accountancy_account_interest
        fkProjet:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_projet
        fkUserAuthor:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user_author
        fkUserModif:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user_modif
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
