Dolibarr\Core\CoreBundle\Entity\LlxMulticurrencyRate:
    type: entity
    table: llx_multicurrency_rate
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateSync:
            type: datetime
            nullable: true
            column: date_sync
        rate:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        fkMulticurrency:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: fk_multicurrency
        entity:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '1'
    lifecycleCallbacks: {  }
