Dolibarr\Core\CoreBundle\Entity\LlxNotify:
    type: entity
    table: llx_notify
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        daten:
            type: datetime
            nullable: true
        fkAction:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: fk_action
        fkSoc:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_soc
        fkContact:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_contact
        fkUser:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user
        type:
            type: string
            nullable: true
            length: 16
            options:
                fixed: false
                default: email
        typeTarget:
            type: string
            nullable: true
            length: 16
            options:
                fixed: false
            column: type_target
        objetType:
            type: string
            nullable: false
            length: 24
            options:
                fixed: false
            column: objet_type
        objetId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: objet_id
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
