Dolibarr\Core\CoreBundle\Entity\LlxOauthToken:
    type: entity
    table: llx_oauth_token
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        service:
            type: string
            nullable: true
            length: 36
            options:
                fixed: false
        token:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        tokenstring:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        fkUser:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user
        fkAdherent:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_adherent
        entity:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '1'
    lifecycleCallbacks: {  }
