Dolibarr\Core\CoreBundle\Entity\LlxOpensurveyUserStuds:
    type: entity
    table: llx_opensurvey_user_studs
    indexes:
        idx_opensurvey_user_studs_id_users:
            columns:
                - id_users
        idx_opensurvey_user_studs_nom:
            columns:
                - nom
        idx_opensurvey_user_studs_id_sondage:
            columns:
                - id_sondage
    id:
        idUsers:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_users
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        idSondage:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
            column: id_sondage
        reponses:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
