Dolibarr\Core\CoreBundle\Entity\LlxPaymentSalary:
    type: entity
    table: llx_payment_salary
    indexes:
        idx_payment_salary_ref:
            columns:
                - num_payment
        idx_payment_salary_user:
            columns:
                - fk_user
                - entity
        idx_payment_salary_datep:
            columns:
                - datep
        idx_payment_salary_datesp:
            columns:
                - datesp
        idx_payment_salary_dateep:
            columns:
                - dateep
        IDX_6C2013911AD0877:
            columns:
                - fk_user
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        datec:
            type: datetime
            nullable: true
        datep:
            type: date
            nullable: true
        datev:
            type: date
            nullable: true
        salary:
            type: float
            nullable: true
            precision: 24
            scale: 8
        amount:
            type: float
            nullable: false
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
        fkTypepayment:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: fk_typepayment
        numPayment:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: num_payment
        label:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        datesp:
            type: date
            nullable: true
        dateep:
            type: date
            nullable: true
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        note:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        fkBank:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_bank
        fkUserAuthor:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user_author
        fkUserModif:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user_modif
    manyToOne:
        fkUser:
            targetEntity: LlxUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_user:
                    referencedColumnName: rowid
            orphanRemoval: false
    lifecycleCallbacks: {  }
