Dolibarr\Core\CoreBundle\Entity\LlxProductAttributeCombination:
    type: entity
    table: llx_product_attribute_combination
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fkProductParent:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: fk_product_parent
        fkProductChild:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: fk_product_child
        variationPrice:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: variation_price
        variationPricePercentage:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: variation_price_percentage
        variationWeight:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: variation_weight
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
    lifecycleCallbacks: {  }
