Dolibarr\Core\CoreBundle\Entity\LlxPropalMergePdfProduct:
    type: entity
    table: llx_propal_merge_pdf_product
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fkProduct:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: fk_product
        fileName:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: file_name
        lang:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
        fkUserAuthor:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user_author
        fkUserMod:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: fk_user_mod
        datec:
            type: datetime
            nullable: false
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        importKey:
            type: string
            nullable: true
            length: 14
            options:
                fixed: false
            column: import_key
    lifecycleCallbacks: {  }
