Dolibarr\Core\CoreBundle\Entity\LlxSocieteCommerciaux:
    type: entity
    table: llx_societe_commerciaux
    uniqueConstraints:
        uk_societe_commerciaux:
            columns:
                - fk_soc
                - fk_user
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fkSoc:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_soc
        fkUser:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user
        importKey:
            type: string
            nullable: true
            length: 14
            options:
                fixed: false
            column: import_key
    lifecycleCallbacks: {  }
