Dolibarr\Core\CoreBundle\Entity\LlxBlockedlogAuthority:
    type: entity
    table: llx_blockedlog_authority
    indexes:
        signature:
            columns:
                - signature
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        blockchain:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        signature:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
