Dolibarr\Core\CoreBundle\Entity\LlxCommandeFournisseur:
    type: entity
    table: llx_commande_fournisseur
    indexes:
        idx_commande_fournisseur_fk_soc:
            columns:
                - fk_soc
        billed:
            columns:
                - billed
    uniqueConstraints:
        uk_commande_fournisseur_ref:
            columns:
                - ref
                - fk_soc
                - entity
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ref:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        refExt:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ref_ext
        refSupplier:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ref_supplier
        fkProjet:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: fk_projet
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        dateCreation:
            type: datetime
            nullable: true
            column: date_creation
        dateValid:
            type: datetime
            nullable: true
            column: date_valid
        dateApprove:
            type: datetime
            nullable: true
            column: date_approve
        dateApprove2:
            type: datetime
            nullable: true
            column: date_approve2
        dateCommande:
            type: date
            nullable: true
            column: date_commande
        fkUserAuthor:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user_author
        fkUserModif:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user_modif
        fkUserValid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user_valid
        fkUserApprove:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user_approve
        fkUserApprove2:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user_approve2
        source:
            type: smallint
            nullable: false
            options:
                unsigned: false
        fkStatut:
            type: smallint
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: fk_statut
        billed:
            type: smallint
            nullable: true
            options:
                unsigned: false
                default: '0'
        amountHt:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
            column: amount_ht
        remisePercent:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: remise_percent
        remise:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
        tva:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
        localtax1:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
        localtax2:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
        totalHt:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
            column: total_ht
        totalTtc:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
            column: total_ttc
        notePrivate:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: note_private
        notePublic:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: note_public
        modelPdf:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: model_pdf
        lastMainDoc:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: last_main_doc
        dateLivraison:
            type: datetime
            nullable: true
            column: date_livraison
        fkAccount:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_account
        fkCondReglement:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_cond_reglement
        fkModeReglement:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_mode_reglement
        fkInputMethod:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: fk_input_method
        fkIncoterms:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_incoterms
        locationIncoterms:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: location_incoterms
        importKey:
            type: string
            nullable: true
            length: 14
            options:
                fixed: false
            column: import_key
        extraparams:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        fkMulticurrency:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_multicurrency
        multicurrencyCode:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: multicurrency_code
        multicurrencyTx:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '1.00000000'
            column: multicurrency_tx
        multicurrencyTotalHt:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
            column: multicurrency_total_ht
        multicurrencyTotalTva:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
            column: multicurrency_total_tva
        multicurrencyTotalTtc:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
            column: multicurrency_total_ttc
    manyToOne:
        fkSoc:
            targetEntity: LlxSociete
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_soc:
                    referencedColumnName: rowid
            orphanRemoval: false
    lifecycleCallbacks: {  }
