Dolibarr\Core\CoreBundle\Entity\LlxCPaperFormat:
    type: entity
    table: llx_c_paper_format
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
        label:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        width:
            type: float
            nullable: true
            precision: 6
            scale: 2
            options:
                default: '0.00'
        height:
            type: float
            nullable: true
            precision: 6
            scale: 2
            options:
                default: '0.00'
        unit:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        module:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
    lifecycleCallbacks: {  }
