Dolibarr\Core\CoreBundle\Entity\LlxCTypeContainer:
    type: entity
    table: llx_c_type_container
    uniqueConstraints:
        uk_c_type_container_id:
            columns:
                - code
                - entity
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        label:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        module:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
