Dolibarr\Core\CoreBundle\Entity\LlxCEcotaxe:
    type: entity
    table: llx_c_ecotaxe
    uniqueConstraints:
        uk_c_ecotaxe:
            columns:
                - code
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        libelle:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        price:
            type: float
            nullable: true
            precision: 24
            scale: 8
        organization:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        fkPays:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: fk_pays
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
