Dolibarr\Core\CoreBundle\Entity\LlxCHrmDepartment:
    type: entity
    table: llx_c_hrm_department
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        pos:
            type: boolean
            nullable: false
            options:
                default: '0'
        code:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
        label:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
