Dolibarr\Core\CoreBundle\Entity\LlxCChargesociales:
    type: entity
    table: llx_c_chargesociales
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        libelle:
            type: string
            nullable: true
            length: 80
            options:
                fixed: false
        deductible:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '0'
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        code:
            type: string
            nullable: false
            length: 12
            options:
                fixed: false
        accountancyCode:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: accountancy_code
        fkPays:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
            column: fk_pays
        module:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
    lifecycleCallbacks: {  }
