Dolibarr\Core\CoreBundle\Entity\LlxCCivility:
    type: entity
    table: llx_c_civility
    uniqueConstraints:
        uk_c_civility:
            columns:
                - code
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 6
            options:
                fixed: false
        label:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        module:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
    lifecycleCallbacks: {  }
