Dolibarr\Core\CoreBundle\Entity\LlxCCountry:
    type: entity
    table: llx_c_country
    uniqueConstraints:
        idx_c_country_code:
            columns:
                - code
        idx_c_country_label:
            columns:
                - label
        idx_c_country_code_iso:
            columns:
                - code_iso
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
        codeIso:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
            column: code_iso
        label:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        favorite:
            type: boolean
            nullable: false
            options:
                default: '0'
    lifecycleCallbacks: {  }
