Dolibarr\Core\CoreBundle\Entity\LlxConst:
    type: entity
    table: llx_const
    uniqueConstraints:
        uk_const:
            columns:
                - name
                - entity
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        value:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        type:
            type: string
            nullable: true
            length: 6
            options:
                fixed: false
        visible:
            type: boolean
            nullable: false
            options:
                default: '1'
        note:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
