Dolibarr\Core\CoreBundle\Entity\LlxCommandeFournisseurExtrafields:
    type: entity
    table: llx_commande_fournisseur_extrafields
    indexes:
        idx_commande_fournisseur_extrafields:
            columns:
                - fk_object
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        fkObject:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: fk_object
        importKey:
            type: string
            nullable: true
            length: 14
            options:
                fixed: false
            column: import_key
    lifecycleCallbacks: {  }
