Dolibarr\Core\CoreBundle\Entity\LlxDeplacement:
    type: entity
    table: llx_deplacement
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ref:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        datec:
            type: datetime
            nullable: false
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        dated:
            type: datetime
            nullable: true
        fkUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: fk_user
        fkUserAuthor:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user_author
        fkUserModif:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user_modif
        type:
            type: string
            nullable: false
            length: 12
            options:
                fixed: false
        fkStatut:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
            column: fk_statut
        km:
            type: float
            nullable: true
            precision: 10
            scale: 0
        fkSoc:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_soc
        fkProjet:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: fk_projet
        notePrivate:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: note_private
        notePublic:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: note_public
        extraparams:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
