Dolibarr\Core\CoreBundle\Entity\LlxPaiementfournFacturefourn:
    type: entity
    table: llx_paiementfourn_facturefourn
    indexes:
        idx_paiementfourn_facturefourn_fk_facture:
            columns:
                - fk_facturefourn
        idx_paiementfourn_facturefourn_fk_paiement:
            columns:
                - fk_paiementfourn
    uniqueConstraints:
        uk_paiementfourn_facturefourn:
            columns:
                - fk_paiementfourn
                - fk_facturefourn
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fkPaiementfourn:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_paiementfourn
        fkFacturefourn:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_facturefourn
        amount:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
        multicurrencyCode:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: multicurrency_code
        multicurrencyTx:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '1.00000000'
            column: multicurrency_tx
        multicurrencyAmount:
            type: float
            nullable: true
            precision: 24
            scale: 8
            options:
                default: '0.00000000'
            column: multicurrency_amount
    lifecycleCallbacks: {  }
