Dolibarr\Core\CoreBundle\Entity\LlxSocietePrices:
    type: entity
    table: llx_societe_prices
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fkSoc:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: fk_soc
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        datec:
            type: datetime
            nullable: true
        fkUserAuthor:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user_author
        priceLevel:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: price_level
    lifecycleCallbacks: {  }
