Dolibarr\Core\CoreBundle\Entity\LlxUserAlert:
    type: entity
    table: llx_user_alert
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: integer
            nullable: true
            options:
                unsigned: false
        fkContact:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_contact
        fkUser:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: fk_user
    lifecycleCallbacks: {  }
