Dolibarr\Core\CoreBundle\Entity\LlxUsergroup:
    type: entity
    table: llx_usergroup
    uniqueConstraints:
        uk_usergroup_name:
            columns:
                - nom
                - entity
    id:
        rowid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        entity:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        datec:
            type: datetime
            nullable: true
        tms:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        note:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        modelPdf:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: model_pdf
    lifecycleCallbacks: {  }
