Dolibarr\Core\CoreBundle\Entity\LlxUserClicktodial:
    type: entity
    table: llx_user_clicktodial
    id:
        fkUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: fk_user
            generator:
                strategy: IDENTITY
    fields:
        url:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        login:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
        pass:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
        poste:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
    lifecycleCallbacks: {  }
